---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download

- hosts: master
  become: true
  roles:
    - role: k3s/master
    - role: k3s/reboot

- hosts: workers
  become: true
  roles:
    - role: k3s/workers
    - role: k3s/reboot

- hosts: localhost
  connection: local
  roles:
    - role: postconfig/localhost
