---
- name: Enable IPv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.builtin.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: install nfs-common on the servers
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Download k3s binary x64
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.architecture == "x86_64"

- name: Check if the token file already exists
  ansible.builtin.stat:
    path: /var/lib/rancher/k3s/server/node-token
  register: token_file_stat
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Generate K3s token
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  when:
    - inventory_hostname in groups['master']
    - inventory_hostname == groups['master'][0]
    - not token_file_stat.stat.exists

  block:
    - name: generate token
      ansible.builtin.shell: |
        /usr/local/bin/k3s token generate
      register: k3s_token

    - name: Store Master node-token
      ansible.builtin.set_fact:
        token: "{{ k3s_token.stdout | split('.') | last }}"

- name: Create K3s config directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

# Master
- name: Include Master tasks
  include_tasks: master.yml
  when:
    - inventory_hostname in groups['master']
    - token is defined

# Workers
- name: Include Workers tasks
  include_tasks: workers.yml
  when:
    - inventory_hostname in groups['workers']
    - token is defined
