k3s_version: v1.31.6+k3s1
ansible_user: sfoley
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--write-kubeconfig-mode=644"
extra_agent_args: ""
copy_kubeconfig: true
argocd: true
metallb: false
metallb_version: "v0.14.9"
metallb_range: "192.168.1.40-192.168.3.49"
