---
- name: Install MetalLB
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml"

- name: Wait for MetalLB controller deployment to be ready
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: controller
    namespace: metallb-system
    wait: true
    wait_timeout: 300

- name: Configure MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    namespace: metallb-system
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default
      spec:
        addresses:
          - "{{ metallb_range }}"

- name: Configure MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    namespace: metallb-system
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default
      spec:
        ipAddressPools:
          - default
