---
- name: Install metallb
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
  changed_when: true

- name: Wait for 60 seconds for metallb to start up
  pause:
    seconds: 60
    prompt: "Waiting 60 seconds for metallb to start up..."

- name: configure metallb range
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: default
      namespace: metallb-system
    spec:
      addresses:
       - {{ metallb_range }}
    EOF
  changed_when: true

- name: configure metallb l2advertisement
  shell: |
    kubectl apply -f - <<EOF
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: default
      namespace: metallb-system
    spec:
      ipAddressPools:
      - default
    EOF
  changed_when: true
