---
- name: Set timezone to America/Los_Angeles
  become: true
  community.general.timezone:
    name: America/Los_Angeles

- name: reboot if new installation
  when: not token_file_stat.stat.exists

  block:
    - name: Reboot after installation
      ansible.builtin.reboot:

    - name: print message after reboot
      ansible.builtin.debug:
        msg: This system has been rebooted
