---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s/nodes
    - role: k3s/reboot

- hosts: localhost
  connection: local
  gather_facts: true
  vars_prompt:
    - name: cloudflare_api_token
      prompt: "Enter your Cloudflare API token"
      private: true
  roles:
    - role: postconfig/localhost
